project:
  type: website

website:
  favicon: images/favicon.ico
  navbar:
    logo: images/logo.png
    background: "#fffbf7"
    left:
      - text: " " 
        href: index.qmd
      - text: "about"
        href: about.qmd
      - text: "projects"
        href: projects.qmd
      - text: "publications"
        href: publications.qmd
      - text: "resources"
        href: resources.qmd
    search: true 
    reader-mode: true

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: false
    
execute:
  freeze: auto    
